services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - maria_db
    restart: unless-stopped

  maria_db:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local

  db_data:
    driver: local